repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-merge-conflict
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
      - id: dead
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.7
    hooks:
      - id: pylint
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
